FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.pkl ./model.pkl
COPY predict.py ./predict.py

EXPOSE 8080
CMD ["python", "predict.py"]
